import os
import re
from pathlib import Path
from typing import Any

import pytest

from oura_exporter.definitions import (
    Category,
    load_definitions,
    parse_definitions,
    render_metric_list,
)

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN METRICS (generated by tests/test_readme.py) -->"
END = "<!-- END METRICS -->"
LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")


def categories(*raw: dict[str, Any]) -> tuple[Category, ...]:
    return parse_definitions({"categories": list(raw)}, "test")


def category(name: str, kind: str, metrics: list[dict[str, Any]], **extra: Any) -> dict[str, Any]:
    return {"name": name, "kind": kind, "prefix": f"oura_{name}_", "metrics": metrics, **extra}


def test_the_readme_metric_list_is_current() -> None:
    text = README.read_text(encoding="utf-8")
    head, found_begin, rest = text.partition(f"{BEGIN}\n")
    block, found_end, tail = rest.partition(END)
    assert found_begin
    assert found_end
    rendered = render_metric_list(load_definitions()) + "\n"
    if os.environ.get("UPDATE_GOLDEN"):
        README.write_text(f"{head}{BEGIN}\n{rendered}{END}{tail}", encoding="utf-8")
        block = rendered
    assert block == rendered


def test_the_readme_has_exactly_one_generated_block() -> None:
    text = README.read_text(encoding="utf-8")
    assert text.count(BEGIN) == 1
    assert text.count(END) == 1
    assert text.index(BEGIN) < text.index(END)


@pytest.mark.parametrize(
    "document",
    [README, ROOT / "docs" / "details.md", ROOT / "CONTRIBUTING.md", ROOT / "SECURITY.md"],
    ids=lambda path: path.name,
)
def test_relative_links_resolve(document: Path) -> None:
    for target in LINK.findall(document.read_text(encoding="utf-8")):
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        assert (document.parent / target.split("#", 1)[0]).exists(), f"{document.name}: {target}"


class TestRenderMetricList:
    def test_one_bullet_per_category_in_yaml_order(self) -> None:
        listed = categories(
            category("zebra", "daily", [{"name": "b", "help": "B."}, {"name": "a", "help": "A."}]),
            category("alpha", "latest", [{"name": "c", "help": "C."}]),
        )
        assert render_metric_list(listed) == (
            "- **Zebra** · `oura_zebra_*` · latest day<br>\n"
            "  `b`, `a`, `timestamp_seconds`\n"
            "- **Alpha** · `oura_alpha_*` · most recent sample<br>\n"
            "  `c`, `timestamp_seconds`"
        )

    def test_timestamp_is_last_and_missing_for_single_documents(self) -> None:
        listed = categories(
            category("profile", "single", [{"name": "age", "help": "Age."}]),
        )
        assert render_metric_list(listed) == (
            "- **Profile** · `oura_profile_*` · profile<br>\n  `age`"
        )

    def test_hints_for_mapped_gauges_state_sets_and_info_metrics(self) -> None:
        listed = categories(
            category(
                "mixed",
                "daily",
                [
                    {"name": "level", "help": "L.", "mapping": {"low": 1, "mid": 2, "high": 5}},
                    {"name": "summary", "help": "S.", "mapping": {"a": 1, "b": 2, "c": 3}},
                    {"name": "source", "help": "S.", "type": "enum", "states": ["x", "y"]},
                    {"name": "sex", "help": "S.", "type": "info"},
                    {"name": "plain", "help": "P."},
                    {"name": "when", "help": "W.", "transform": "timestamp"},
                ],
                title="Mixed bag",
                summary="whenever",
            )
        )
        assert render_metric_list(listed) == (
            "- **Mixed bag** · `oura_mixed_*` · whenever<br>\n"
            "  `level (1-5)`, `summary (1-3)`, `source (state set)`, `sex_info`, `plain`, `when`, "
            "`timestamp_seconds`"
        )

    def test_fractional_mappings_keep_their_decimals(self) -> None:
        listed = categories(
            category(
                "frac", "single", [{"name": "m", "help": "M.", "mapping": {"a": 0.5, "b": 2.25}}]
            )
        )
        assert "`m (0.5-2.25)`" in render_metric_list(listed)

    def test_every_metric_of_the_packaged_definitions_is_listed(self) -> None:
        rendered = render_metric_list(load_definitions())
        for definition in load_definitions():
            assert f"`{definition.prefix}*`" in rendered
            for metric in definition.metrics:
                assert f"`{metric.name}" in rendered
        assert "…" not in rendered

    def test_no_categories(self) -> None:
        assert render_metric_list([]) == ""
