import os
import re
from pathlib import Path
from typing import Any

import pytest

from oura_exporter.definitions import (
    Category,
    load_definitions,
    parse_definitions,
    render_metric_list,
)

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN METRICS (generated by tests/test_readme.py) -->"
END = "<!-- END METRICS -->"
LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
TOKEN = re.compile(r"`([^`]+)`")


def categories(*raw: dict[str, Any]) -> tuple[Category, ...]:
    return parse_definitions({"categories": list(raw)}, "test")


def category(name: str, kind: str, metrics: list[dict[str, Any]], **extra: Any) -> dict[str, Any]:
    return {"name": name, "kind": kind, "prefix": f"oura_{name}_", "metrics": metrics, **extra}


def test_the_readme_metric_list_is_current() -> None:
    text = README.read_text(encoding="utf-8")
    head, found_begin, rest = text.partition(f"{BEGIN}\n")
    block, found_end, tail = rest.partition(END)
    assert found_begin
    assert found_end
    rendered = render_metric_list(load_definitions()) + "\n"
    if os.environ.get("UPDATE_GOLDEN"):
        README.write_text(f"{head}{BEGIN}\n{rendered}{END}{tail}", encoding="utf-8")
        block = rendered
    assert block == rendered


def test_the_readme_has_exactly_one_generated_block() -> None:
    text = README.read_text(encoding="utf-8")
    assert text.count(BEGIN) == 1
    assert text.count(END) == 1
    assert text.index(BEGIN) < text.index(END)


@pytest.mark.parametrize(
    "document",
    [README, ROOT / "docs" / "details.md", ROOT / "CONTRIBUTING.md", ROOT / "SECURITY.md"],
    ids=lambda path: path.name,
)
def test_relative_links_resolve(document: Path) -> None:
    for target in LINK.findall(document.read_text(encoding="utf-8")):
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        assert (document.parent / target.split("#", 1)[0]).exists(), f"{document.name}: {target}"


class TestRenderMetricList:
    def test_one_bullet_per_category_in_yaml_order(self) -> None:
        listed = categories(
            category("zebra", "daily", [{"name": "b", "help": "B."}, {"name": "a", "help": "A."}]),
            category("alpha", "latest", [{"name": "c", "help": "C."}]),
        )
        assert render_metric_list(listed) == (
            "- **Zebra** · `oura_zebra_*` · latest day<br>\n"
            "  `b`, `a`, `timestamp_seconds`\n"
            "- **Alpha** · `oura_alpha_*` · most recent sample<br>\n"
            "  `c`, `timestamp_seconds`"
        )

    def test_timestamp_is_last_and_missing_for_single_documents(self) -> None:
        listed = categories(
            category("profile", "single", [{"name": "age", "help": "Age."}]),
        )
        assert render_metric_list(listed) == (
            "- **Profile** · `oura_profile_*` · profile<br>\n  `age`"
        )

    def test_hints_for_mapped_gauges_state_sets_and_info_metrics(self) -> None:
        listed = categories(
            category(
                "mixed",
                "daily",
                [
                    {"name": "level", "help": "L.", "mapping": {"low": 1, "mid": 2, "high": 5}},
                    {"name": "summary", "help": "S.", "mapping": {"a": 1, "b": 2, "c": 3}},
                    {"name": "source", "help": "S.", "type": "enum", "states": ["x", "y"]},
                    {"name": "sex", "help": "S.", "type": "info"},
                    {"name": "plain", "help": "P."},
                    {"name": "when", "help": "W.", "transform": "timestamp"},
                ],
                title="Mixed bag",
                summary="whenever",
            )
        )
        assert render_metric_list(listed) == (
            "- **Mixed bag** · `oura_mixed_*` · whenever<br>\n"
            "  `level (1-5)`, `summary (1-3)`, `source (state set)`, `sex_info`, `plain`, `when`, "
            "`timestamp_seconds`"
        )

    def test_fractional_mappings_keep_their_decimals(self) -> None:
        listed = categories(
            category(
                "frac", "single", [{"name": "m", "help": "M.", "mapping": {"a": 0.5, "b": 2.25}}]
            )
        )
        assert "`m (0.5-2.25)`" in render_metric_list(listed)

    def test_every_metric_of_the_packaged_definitions_is_listed_on_its_own_line(self) -> None:
        definitions = load_definitions()
        blocks: list[list[str]] = []
        for line in render_metric_list(definitions).split("\n"):
            if line.startswith("- "):
                blocks.append([line])
            else:
                blocks[-1].append(line)
        assert len(blocks) == len(definitions)
        for definition, (header, *lines) in zip(definitions, blocks, strict=True):
            assert f"`{definition.prefix}*`" in header
            contributor_lines = [
                line for line in lines if line.lstrip().startswith("contributors (")
            ]
            name_lines = [line for line in lines if line not in contributor_lines]
            listed = [token.split(" (")[0] for token in TOKEN.findall(" ".join(name_lines))]
            listed_contributors = [
                token.split(" (")[0]
                for token in TOKEN.findall(" ".join(contributor_lines))
                if token != "contributors_*"
            ]
            expected = [
                f"{metric.name}_info" if metric.type == "info" else metric.name
                for metric in definition.metrics
                if not metric.name.startswith("contributors_")
            ]
            if definition.timestamp_name is not None:
                expected.append("timestamp_seconds")
            assert listed == expected, definition.name
            assert listed_contributors == [
                metric.name.removeprefix("contributors_")
                for metric in definition.metrics
                if metric.name.startswith("contributors_")
            ], definition.name
            assert bool(contributor_lines) == bool(listed_contributors), definition.name

    def test_contributors_get_their_own_line_without_the_prefix(self) -> None:
        listed = categories(
            category(
                "zebra",
                "daily",
                [
                    {"name": "score", "help": "S."},
                    {"name": "contributors_a", "help": "A."},
                    {"name": "contributors_b", "help": "B."},
                ],
            )
        )
        assert render_metric_list(listed) == (
            "- **Zebra** · `oura_zebra_*` · latest day<br>\n"
            "  `score`, `timestamp_seconds`<br>\n"
            "  contributors (`contributors_*`): `a`, `b`"
        )

    def test_contributors_are_separated_wherever_they_are_defined(self) -> None:
        listed = categories(
            category(
                "mixed",
                "latest",
                [
                    {"name": "contributors_x", "help": "X."},
                    {"name": "level", "help": "L.", "mapping": {"a": 1, "b": 3}},
                    {"name": "contributors_grade", "help": "G.", "mapping": {"a": 2, "b": 4}},
                    {"name": "top_contributors", "help": "T."},
                ],
            )
        )
        assert render_metric_list(listed) == (
            "- **Mixed** · `oura_mixed_*` · most recent sample<br>\n"
            "  `level (1-3)`, `top_contributors`, `timestamp_seconds`<br>\n"
            "  contributors (`contributors_*`): `x`, `grade (2-4)`"
        )

    def test_single_documents_have_no_timestamp_but_may_have_contributors(self) -> None:
        listed = categories(
            category(
                "profile",
                "single",
                [{"name": "age", "help": "A."}, {"name": "contributors_a", "help": "C."}],
            ),
            category(
                "solo", "single", [{"name": "contributors_a", "help": "A."}], summary="only these"
            ),
        )
        assert render_metric_list(listed) == (
            "- **Profile** · `oura_profile_*` · profile<br>\n"
            "  `age`<br>\n"
            "  contributors (`contributors_*`): `a`\n"
            "- **Solo** · `oura_solo_*` · only these<br>\n"
            "  contributors (`contributors_*`): `a`"
        )

    def test_categories_without_contributors_keep_the_two_line_form(self) -> None:
        rendered = render_metric_list(load_definitions())
        for line in rendered.split("\n"):
            if line.lstrip().startswith("`") and "<br>" not in line:
                assert "contributors" not in line
        assert "- **Heart rate** · `oura_heartrate_*` · most recent sample<br>\n  `bpm`" in rendered

    def test_no_categories(self) -> None:
        assert render_metric_list([]) == ""
